version: "2"
services:
  node:
    image: "node:14"
    working_dir: /usr/opis-scraper/src
    volumes:
      - ./:/usr/opis-scraper/src
    command: bash -c "npm run dev"

  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=opis_manager
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"