CREATE TABLE schede_opis (
    id int NOT NULL AUTO_INCREMENT,
    anno_accademico varchar(255),
    totale_schede int,
    totale_schede_nf int,
    femmine int,
    femmine_nf int,
    fc int,
    inatt int,
    inatt_nf int,
    eta JSON,
    anno_iscr JSON,
    num_studenti JSON,
    ragg_uni JSON,
    studio_gg JSON,
    studio_tot JSON,
    domande JSON,
    domande_nf JSON,
    motivo_nf JSON,
    sugg JSON,
    sugg_nf JSON,
    id_insegnamento int,
    PRIMARY KEY (id),
    FOREIGN KEY (id_insegnamento) REFERENCES insegnamento(id)
)